SEMANTIC_SCHEMA = {
    "type": "object",
    "properties": {
        "canonical_goal": {"type": "string"},
        "language": {"type": "string", "enum": ["en", "ar", "mixed", "other"]},
        "domain": {"type": "string"},
        "confidence": {"type": "number"},
        "speech_act": {"type": "string", "enum": ["question", "request", "command", "statement", "correction", "unknown"]},
        "actionability": {"type": "string", "enum": ["action", "information", "conversation", "correction", "unknown"]},
        "requires_fresh_data": {"type": "boolean"},
        "intents": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "confidence": {"type": "number"},
                "evidence": {"type": "array", "items": {"type": "string"}},
                "capability": {"type": "string"},
                "required_slots": {"type": "array", "items": {"type": "string"}},
                "missing_slots": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["name", "confidence", "evidence", "capability", "required_slots", "missing_slots"],
            "additionalProperties": False,
        }},
        "entities": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "type": {"type": "string"},
                "normalized": {"type": "string"},
                "confidence": {"type": "number"},
                "start": {"type": "integer"},
                "end": {"type": "integer"},
                "canonical": {"type": "string"},
            },
            "required": ["text", "type", "normalized", "confidence", "start", "end", "canonical"],
            "additionalProperties": False,
        }},
        "references": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "kind": {"type": "string"},
                "target": {"type": "string"},
                "resolved": {"type": "boolean"},
                "confidence": {"type": "number"},
                "basis": {"type": "string"},
            },
            "required": ["text", "kind", "target", "resolved", "confidence", "basis"],
            "additionalProperties": False,
        }},
        "temporal": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "kind": {"type": "string"},
                "start": {"type": "string"},
                "end": {"type": "string"},
                "granularity": {"type": "string"},
                "timezone": {"type": "string"},
                "confidence": {"type": "number"},
            },
            "required": ["text", "kind", "start", "end", "granularity", "timezone", "confidence"],
            "additionalProperties": False,
        }},
        "constraints": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "key": {"type": "string"},
                "operator": {"type": "string"},
                "value": {"type": "string"},
                "confidence": {"type": "number"},
            },
            "required": ["key", "operator", "value", "confidence"],
            "additionalProperties": False,
        }},
        "slots": {"type": "object", "additionalProperties": {"type": "string"}},
        "required_information": {"type": "array", "items": {"type": "string"}},
        "ambiguity_reasons": {"type": "array", "items": {"type": "string"}},
        "safety_signals": {"type": "array", "items": {"type": "string"}},
        "needs_clarification": {"type": "boolean"},
        "clarification_question": {"type": "string"},
    },
    "required": [
        "canonical_goal", "language", "domain", "confidence", "speech_act", "actionability",
        "requires_fresh_data", "intents", "entities",
        "references", "temporal", "constraints", "slots", "required_information",
        "ambiguity_reasons", "safety_signals", "needs_clarification", "clarification_question",
    ],
    "additionalProperties": False,
}
